### ISSUE TITLE
Critical Leak : PHBridgeSendAPI - (PHRequest *)updateLightStateForId:(NSString *)lightIdentifier withLightState:(PHLightState *)lightState completionHandler:(PHBridgeSendErrorArrayCompletionHandler)completionHandler;

### ISSUE THREAD

**Issue by false** [PhilipsHue/PhilipsHueSDK-iOS-OSX#75] opened 2014-11-06 23:03 UTC
If you call that method in a loop you can clearly see through Xcode Instruments Allocation tools that there is a leak with the requests (CFNetwork, URLResponse, URLRequest ...).

It leads to the crash of my application on the middle term (10-20 minutes) as I call the method quite often.

Could you fix the leak, as we don't have access to the SDK sources?

Quick Exemple : 
UIColor* color = [UIColor whiteColor];
for(int i=0; i<100000; i++) {
                    CGPoint xy = [PHUtilities calculateXY:color forModel:light.modelNumber];

                    PHLightState *lightState = [[PHLightState alloc] init];
                    lightState.x = @(xy.x);
                    lightState.y = @(xy.y);

                    [self.bridgeSendAPI updateLightStateForId:light.identifier withLightState:lightState completionHandler:^(NSArray *errors) {
                        if (errors != nil) {
                            NSString *message = [NSString stringWithFormat:@"%@: %@", NSLocalizedString(@"Errors", @""), errors != nil ? errors : NSLocalizedString(@"none", @"")];
                            
                            NSLog(@"Response: %@",message);
                        }
                    }];
}

**Comment by lightbow** [comment] 2015-04-05 14:33
I believe Philips just needs to change their code from using NSURLConnection to using NSURLSession. From much experimentation, there's no other way to avoid the memory leak. While the old way should be fine for many apps, Lightbow's animations sometimes shoot out hundreds of light state changes, and with the memory leak down in iOS with no viable workarounds I could find, I was forced to write my own light-state-dispatch code using the more modern NSURLSession. @pverh  I would love to ditch my code and switch back to using the Philips SDK for this! For those of you needing a solution while we wait for a fix in the SDK, here's some Swift code that might be helpful, showing how to easily turn a json dictionary into a NSURLRequest/NSURLSession. (ignore the LB-specific stuff... this is just to hopefully save folks some time in figuring out the specifics of some of the constants)


```
func submitJSON(json: AnyObject, post: Bool, path: String, successHandler: ((NSURLResponse!,NSData)->Void)?, failureHandler: (()->Void)?)
    {
        var error: NSError?
        let data = NSJSONSerialization.dataWithJSONObject(json, options: nil, error: &error)
        LBErrorAndWarningController.sharedController().reportError(error)

        if error != nil {
            failureHandler?()
            return
        }
        
        let url = NSURL(string: path)
        let request = NSMutableURLRequest(URL: url!)
        
        request.HTTPMethod = post ? "POST" : "PUT"
        request.setValue("application/json", forHTTPHeaderField: "Accept")
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        request.cachePolicy = .ReloadIgnoringLocalCacheData
        request.setValue("\(data?.length)", forHTTPHeaderField: "Content-Length")
        request.HTTPBody = data
        
        let task = NSURLSession.sharedSession().dataTaskWithRequest(request, completionHandler: { (responseData, response, connectionError) -> Void in
            
            LBErrorAndWarningController.sharedController().reportError(connectionError)
            
            if connectionError == nil {
                successHandler?(response, responseData)
            } else {
                failureHandler?()
            }
        })
        task.resume()
}
```

**Comment by pverh** [comment] 2015-04-15 13:32
Sorry for the late response. We are currently investigating this issue. Could some of you please provide a minimal piece of reproduction code in which they experience the leak? Thanks!

**Comment by false** [comment] 2015-04-19 19:32
Hello pverh,

You should reproduce the leak with that piece of code :


UIColor* color = [UIColor whiteColor];
for(int i=0; i<100000; i++) {
CGPoint xy = [PHUtilities calculateXY:color forModel:light.modelNumber];

                PHLightState *lightState = [[PHLightState alloc] init];
                lightState.x = @(xy.x);
                lightState.y = @(xy.y);

                [self.bridgeSendAPI
updateLightStateForId:light.identifier withLightState:lightState
completionHandler:^(NSArray *errors) {
                    if (errors != nil) {
                        NSString *message = [NSString
stringWithFormat:@"%@: %@", NSLocalizedString(@"Errors", @""), errors
!= nil ? errors : NSLocalizedString(@"none", @"")];

                        NSLog(@"Response: %@",message);
                    }
                }];

}



Best,

**Comment by pverh** [comment] 2015-04-29 08:13
@false I'm currently investigating this issue and tried your example code in the QuickStart app and it doesn't appear to be leaking after warming up when setting the counter to 500 and performing it repeatedly. It is true that while performing lots of request in a loop the memory footprint rises rapidly but this is only because they http requests will not be released until the requests finish (timeout/fail or have a successful response). When firing more request then the number of request that finish the memory footprint starts to increase.

@macmantrl @bmaltais Do you still have these issues? could you share some example code as well?

**Comment by false** [comment] 2015-04-29 19:16
@pverh The thing is the memory leak should not happen.
In the case of my application that sends about 4 requests every seconds, the application freezes after 10 - 15 minutes. And if I set the limit it to 1 request every second, the problem still occurs 30-40 minutes.

On the application side, we can't control the fact that too many requests are still in suspend ; And in the case of a "big" loop the framework should queue the requests ( and/or ignore some of them?).

Do you use the NSURLSession?
Do you queue the requests?

**Comment by lightbow** [comment] 2015-04-29 19:29
I also recommend making the switch to the more modern NSURLSession. The older NSURLConnection stuff has some long-standing leaks (even with some of the cache-clearing hacks you can find on stackoverflow) and it looks like Apple isn't planning on fixing them since NSURLSession is the future. Here's some more background information: http://www.objc.io/issue-5/from-nsurlconnection-to-nsurlsession.html

**Comment by pverh** [comment] 2015-05-12 15:30
@false Unfortunately we are currently not queueing requests, they are executed right away. If you want a queue you will have to implement it yourself. 
We also don't use NSURLSession at this moment. We are looking into refactoring our connection logic and using NSURLSession, but as the impact is considered high this will not be in the upcoming SDK release. 

I have spotted some issues with the current implementation that I would like to share: 
- Don't schedule light state updates on background queues, as our implementation requires a runloop to be present in order to break a retain cycle (this will be fixed in the next release). 
- As mentioned earlier, be careful when doing lot's of requests in a loop as the calls to PHBridgeSendAPI are not blocking and requests are retained until they get a response or timeout. Two calls per second seems like a safe rate, if you want to have a higher rate, it's advised to chain requests with a queuing mechanism of your own (to ensure memory will be released before new requests are getting called).

**Comment by lightbow** [comment] 2015-06-05 19:08
Light commands spaced out at 0.1s already seemed like a frustrating limitation, and limits what we can do with light animations, especially on many-light setups. It would be a huge problem to increase this to 0.5s (two calls per second). Lightbow currently uses its own custom Swift / NSURLSession-based light state dispatch and caching system, but I wish I could toss it out and use the standard Philips one in your SDK one day. (I originally wrote my own to avoid the leak that's the subject of this thread)

**Comment by false** [comment] 2015-08-04 08:52
Any update on the leak issue?

**Comment by jhvdb87** [comment] 2015-11-19 09:28
We switched to NSURLSession in the 1.11 release and we also did a memory leak fix mentioned by pverh.

**Closed by jhvdb87** 2015-11-19 09:28 UTC
Labels: bug
